# Generated by Django 2.2.3 on 2019-08-21 07:07

import category_team.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category_team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150)),
                ('photo', models.URLField(max_length=150)),
                ('video', models.URLField(max_length=150)),
                ('source', models.CharField(choices=[(category_team.models.SocialNetworkChoice('Facebook'), 'Facebook'), (category_team.models.SocialNetworkChoice('Twitter'), 'Twitter'), (category_team.models.SocialNetworkChoice('Google'), 'Google')], max_length=8)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category_team.Category')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category_team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(to='article.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
