# Generated by Django 2.2.3 on 2019-09-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190906_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
