# Generated by Django 2.2.3 on 2019-09-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190912_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, to='articles.Comment'),
        ),
    ]
