# Generated by Django 2.2.3 on 2019-09-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190913_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.URLField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
