# Generated by Django 2.2.3 on 2019-09-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
