# Generated by Django 2.2.3 on 2019-09-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='published_date',
        ),
    ]
