# Generated by Django 2.2.3 on 2019-08-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
