# Generated by Django 2.2.3 on 2019-08-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_id',
        ),
    ]
