<<<<<<< HEAD
# Generated by Django 2.2.3 on 2019-08-27 10:54
=======
# Generated by Django 2.2.3 on 2019-08-27 10:58
>>>>>>> 5e09fd09c7fa443cb7c8a6b027a54060e5751ad3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190820_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
