# Generated by Django 2.2.3 on 2019-09-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20190906_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
